---
ENGINE_CONFIG: 
    dialect:  sqlite
    path: '////home/dowwie/yosai_alchemystore/yosai_alchemystore/conf/yosai_accounts.db'
    userid:
    password:
    hostname:
    port:
    db:
    echo: True 
